name: Deploy FastAPI with Bedrock and Frontend to AWS

on:
  push:
    branches:
      - main2  # Update if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  # Ensure this matches your FastAPI environment

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Frontend dependencies
      run: |
        cd frontend  # Navigate to your frontend directory if applicable
        npm install
        npm run build  # If you're using a build tool like Webpack, Vite, etc.

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        source: "./"
        target: "/home/ubuntu/your-app-directory"  # Update with your app directory

    - name: Execute SSH commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /home/ubuntu/your-app-directory  # Update with your app directory
          sudo systemctl restart your-fastapi-app.service  # Restart FastAPI service to apply changes
